# Default to dracula theme
general.import = ["/home/hashim/dotfiles/alacritty/dracula.toml"]

[window]
opacity = 0.85
padding = {x = 10, y = 10}

[colors.primary]
background = "#282A36"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

