# Default to dracula theme
general.import = ["/home/hashim/dotfiles/alacritty/tokyo-night-default.toml"]

[window]
opacity = 0.80
padding = {x = 10, y = 10}

[colors.primary]
background = "#000C16"
foreground = "#00FFFF"

[colors.cursor]
background = "#000C16"
foreground = "#00FFFF"

[colors.selection]
text = "#00FFFF"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

