#!/bin/sh

killall -q picom xwinwrap sxhkd dunst
pgrep -x sxhkd > /dev/null || sxhkd &

# feh --bg-center ~/.config/wallpapers/city/bedroom_night_city-1920x1080.png

$HOME/.config/polybar/launch.sh &
sleep 0.2
picom --config $HOME/.config/picom/picom.conf &
xmodmap $HOME/.Xmodmap &
dunst &

if xrandr | grep "HDMI-A-0 connected" >/dev/null && xrandr | grep "DisplayPort-1 connected" >/dev/null; then
    xrandr --output HDMI-A-0 --primary --left-of DisplayPort-1
    bspc wm --reorder-monitors HDMI-A-0 DisplayPort-1
    bspc monitor HDMI-A-0 -d 1 2 3 4 5
    bspc monitor DisplayPort-1 -d 6 7 8 9 10
elif xrandr | grep "HDMI-A-0 connected" >/dev/null; then
    xrandr --output HDMI-A-0 --primary
    bspc wm --reorder-monitors HDMI-A-0
    bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10
elif xrandr | grep "DisplayPort-1 connected" >/dev/null; then
    xrandr --output DisplayPort-1 --primary
    bspc wm --reorder-monitors DisplayPort-1
    bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9 10
else
    echo "No monitors detected, using fallback single monitor setup"
    # Assign all desktops to a dummy monitor (usually the first detected or default)
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor -f ^1

fi
bspc desktop --focus 1

# Active window border color
bspc config focused_border_color "#00FFFF"

# Live wallpaper
xwinwrap -b -nf -ov -ni -g 1920x1080+1920+0 -- mpv -wid WID --fps=30 -vo=gpu --hwdec=auto ~/.config/wallpapers/animated/bedroom_futuristic_night_1920_1080.mp4 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings & 

xwinwrap -b -ov -nf -ni -g 1920x1080+0+0 -- mpv -wid WID --fps=30 -vo=gpu --hwdec=auto ~/.config/wallpapers/animated/bedroom_futuristic_night_1920_1080.mp4 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings &


bspc config border_width         2
bspc config window_gap         	 22
bspc config top_padding 		 35 

bspc config split_ratio          0.52
bspc config borderless_monocle   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
