[module/tray]
type = internal/tray

tray-spacing = 10pt
tray-background= #FFFFFFF
tray-size = 80%

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted =%{T2}%{T1} %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
bar-volume-width                = 8
bar-volume-gradient             = false
bar-volume-indicator            = ""
bar-volume-indicator-foreground = ${colors.secondary}
bar-volume-fill                 = 
bar-volume-fill-foreground      = ${colors.secondary}
bar-volume-empty                = 
bar-volume-empty-foreground     = ${colors.secondary}
bar-volume-background           = ${colors.background}
bar-volume-empty-background     = ${colors.background}
bar-volume-fill-background      = ${colors.background}
bar-volume-indicator-background = ${colors.background}

; Define the icons
format-volume-prefix-foreground = ${colors.light-gray}
format-volume-prefix = "%{T2}󰕿"
 
format-volume = %{T-} <label-volume>
label-volume = %percentage%%

ramp-volume-0 = "󰕿"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰕾"

label-muted = "%{T2}󰝟 %{T-}0%"
label-muted-foreground = ${colors.disabled}

[module/bspwm]
type = internal/bspwm

label-empty = "%{T2}"
label-empty-padding = 2
label-empty-foreground = ${colors.primary}

label-active = "%{T2}󰄮"
label-active-background = ${colors.background-alt}
label-active-padding = 2
label-active-underline = ${colors.primary}

label-occupied ="%{T2}󰡖"
label-occupied-padding = 2
label-occupied-foreground = ${colors.accent}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "%{T2} "
format-prefix-foreground = ${colors.primary}
label = %{T1}%percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "%{T2} %{T1}"
format-prefix-foreground = ${colors.accent}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <ramp-signal> <label-connected>
ramp-signal-0 = 1
ramp-signal-1 = 2
ramp-signal-2 = 3
ramp-signal-3 = 4
ramp-signal-4 = 5
ramp-signal-5 = 6
;format-disconnected = <label-disconnected>
;label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
interface = wlp6s0
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
interface = enp9s0
;label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %I:%M
date-alt = %Y %B %d      %I:%M:%S

label = %date%
label-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true
