[module/tray]
type = internal/tray

tray-spacing = 10pt
tray-background= ${colors.background} 
tray-transparent = true
tray-size = 80%

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted =%{T2}%{T1} %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
bar-volume-width                = 8
bar-volume-gradient             = false
bar-volume-indicator            = ""
bar-volume-indicator-foreground = ${colors.secondary}
bar-volume-fill                 = 
bar-volume-fill-foreground      = ${colors.secondary}
bar-volume-empty                = 
bar-volume-empty-foreground     = ${colors.secondary}
bar-volume-background           = ${colors.background}
bar-volume-empty-background     = ${colors.background}
bar-volume-fill-background      = ${colors.background}
bar-volume-indicator-background = ${colors.background}

; Define the icons
format-volume-prefix-foreground = #FF69B4
format-volume = "%{T2}<ramp-volume> %{T-}<label-volume>"
background = #008080
 
label-volume = %percentage%%

ramp-volume-0 = "󰖀"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰕾"

ramp-volume-0-foreground = ${colors.hot-pink}
ramp-volume-1-foreground = ${colors.hot-pink}
ramp-volume-foreground = ${colors.hot-pink}

format-muted = <label-muted>
format-muted-prefix = "%{T2} 󰝟"  
label-muted = "%{T1} 0%"
format-muted-prefix-foreground = ${colors.hot-pink}

[module/bspwm]
type = internal/bspwm

label-empty = "%{T2}"
label-empty-padding = 2
label-empty-foreground = ${colors.primary}

label-active = "%{T2}"
label-active-foreground = ${colors.electric-cyan} 
label-active-background = ${colors.background-alt}
label-active-padding = 2
label-active-underline = ${colors.primary}

label-occupied ="%{T2}󰡖"
label-occupied-padding = 2
label-occupied-foreground = ${colors.accent}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.cyan}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.accent}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <ramp-signal> <label-connected>
format-disconnected = <label-disconnected>
;label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥 
ramp-signal-4 = 󰤨 

ramp-signal-0-foreground = ${colors.hot-pink} 
ramp-signal-1-foreground = ${colors.hot-pink} 
ramp-signal-2-foreground = ${colors.hot-pink} 
ramp-signal-3-foreground = ${colors.hot-pink} 
ramp-signal-4-foreground = ${colors.hot-pink} 

inherit = network-base
interface-type = wireless
interface = wlp6s0
label-connected = " %essid%"
label-foreground = ${colors.hot-pink}

[module/eth]
inherit = network-base
interface-type = wired
interface = enp9s0

format-connected = <label-connected> 
format-disconnected = <label-disconnected>
label-prefix = "1"
label-connected = "  %local_ip%"
label-disconnected = "󰈀"

label-connected-foreground = ${colors.accent}
label-disconnected-foreground = ${colors.accent}

[module/date]
type = internal/date
interval = 1

date = %I:%M
date-alt = %Y %B %d %I:%M:%S

label = %date%
label-foreground = ${colors.cyan} 

[settings]
screenchange-reload = true
pseudo-transparency = true
