[module/tray]
type = internal/tray

tray-spacing = 10pt
tray-background= ${colors.background} 
tray-transparent = true
tray-size = 80%

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = true

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted =%{T2}%{T1} %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
bar-volume-width                = 8
bar-volume-gradient             = false
bar-volume-indicator            = ""
bar-volume-indicator-foreground = ${colors.neon-magenta}
bar-volume-fill                 = 
bar-volume-fill-foreground      = ${colors.neon-magenta}
bar-volume-empty                = - 
bar-volume-empty-foreground     = ${colors.neon-magenta}
bar-volume-background           = ${colors.background}
bar-volume-empty-background     = ${colors.background}
bar-volume-fill-background      = ${colors.background}
bar-volume-indicator-background = ${colors.background}

; Define the icons
format-volume = "%{T2}<ramp-volume>%{T-} <label-volume>"
click-right = pavucontrol

label-volume = %percentage%%
label-volume-foreground = ${colors.primary}

ramp-volume-0 = "󰖀"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰕾"

ramp-volume-0-foreground = ${colors.primary}
ramp-volume-1-foreground = ${colors.primary}
ramp-volume-foreground = ${colors.primary}

format-muted = <label-muted>
format-muted-prefix = "%{T2}󰝟 "  
label-muted = "%{T1}0%"
format-muted-foreground = ${colors.disabled}

[module/bspwm]
type = internal/bspwm

label-empty = "%{T2}"
label-empty-padding = 2
label-empty-foreground = ${colors.cyan}

label-active = "%{T2}"
label-active-foreground = ${colors.cyan} 
label-active-background = ${colors.background-alt}
label-active-padding = 2
label-active-underline = ${colors.primary}

label-occupied ="%{T2}󰡖"
label-occupied-padding = 2
label-occupied-foreground = ${colors.neon-magenta}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.cyan}
label = %percentage_used:2%%
label-foreground = ${colors.cyan}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.primary}
format-margin =0 
label-foreground = ${colors.primary}

[network-base]
type = internal/network
interval = 5
format-connected = <ramp-signal>  <label-connected>
format-disconnected = <label-disconnected>
;label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
interval = 3
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥 
ramp-signal-4 = 󰤨 

ramp-signal-0-foreground = ${colors.cyan} 
ramp-signal-1-foreground = ${colors.cyan} 
ramp-signal-2-foreground = ${colors.cyan} 
ramp-signal-3-foreground = ${colors.cyan} 
ramp-signal-4-foreground = ${colors.cyan} 

inherit = network-base
interface-type = wireless
interface = wlp6s0
label-connected = ""
label-connected-foreground = ${colors.cyan}
label-disconnected-foreground = ${colors.disabled}

[module/eth]
interval = 3
inherit = network-base
interface-type = wired
interface = enp9s0

format-connected = <label-connected> 
format-disconnected = <label-disconnected>
label-prefix = "1"
label-connected = ""
label-disconnected = "󰈀"

format-connected-margin = 0

label-connected-foreground = ${colors.primary}
label-disconnected-foreground = ${colors.disabled}

[module/date]
type = internal/date
interval = 1

date = "%a %I:%M %p"
date-alt = %A, %B %d, %Y, %I:%M:%S

label = %date%
label-foreground = ${colors.cyan} 

[module/terminal]
type = custom/text
content = "%{T3} "
content-foreground = ${colors.cyan}
click-left = alacritty

[module/vscode]
type = custom/text
content = "%{T3} "
content-foreground = ${colors.cyan}
click-left = code 

[module/clion]
type = custom/text
content = "%{T3} "
content-foreground = ${colors.cyan}
click-left = clion 

[module/pycharm]
type = custom/text
content = "%{T3} "
content-foreground = ${colors.cyan}
click-left = pycharm-professional

[settings]
screenchange-reload = true
pseudo-transparency = true

